name: pmurt

on:
  pull_request:
  push:
    branches: [ development ]
    tags: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  java_version: 17
  java_distribution: zulu
  groovy_version: 4.x

jobs:

  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: ${{ env.java_distribution }}
      - name: build
        run: echo doggies > coatjava.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: coatjava.tar.gz

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: coatjava.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: coatjava.tar.gz

  final:
    needs:
      - build
      - release
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: exit 0

